services:
  mongodb:
    image: mongo
    container_name: snailmail-mongodb
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: snailmail-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: snailmail-mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
volumes:
  mongo-data: